export const EXERCISE_LIST_REQUEST = "EXERCISE_LIST_REQUEST";
export const EXERCISE_LIST_SUCCESS = "EXERCISE_LIST_SUCCESS";
export const EXERCISE_LIST_FAIL = "EXERCISE_LIST_FAIL";

export const EXERCISE_ID_REQUEST = "EXERCISE_ID_REQUEST";
export const EXERCISE_ID_SUCCESS = "EXERCISE_ID_SUCCESS";
export const EXERCISE_ID_FAIL = "EXERCISE_ID_FAIL";

export const EXERCISE_ADD_REQUEST = "EXERCISE_ADD_REQUEST";
export const EXERCISE_ADD_SUCCESS = "EXERCISE_ADD_SUCCESS";
export const EXERCISE_ADD_FAIL = "EXERCISE_ADD_FAIL";

export const EXERCISE_UPDATE_REQUEST = "EXERCISE_UPDATE_REQUEST";
export const EXERCISE_UPDATE_SUCCESS = "EXERCISE_UPDATE_SUCCESS";
export const EXERCISE_UPDATE_FAIL = "EXERCISE_UPDATE_FAIL";

export const USER_LIST_REQUEST = "USER_LIST_REQUEST";
export const USER_LIST_SUCCESS = "USER_LIST_SUCCESS";
export const USER_LIST_FAIL = "USER_LIST_FAIL";

export const CREATE_USER_REQUEST = "CREATE_USER_REQUEST";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_FAIL = "CREATE_USER_FAIL";

export const EXERCISE_DELETE_REQUEST = "EXERCISE_DELETE_REQUEST";
export const EXERCISE_DELETE_SUCCESS = "EXERCISE_DELETE_SUCCESS";
export const EXERCISE_DELETE_FAIL = "EXERCISE_DELETE_FAIL";
