export const EXERCISE_LIST_REQUEST = "EXERCISE_LIST_REQUEST";
export const EXERCISE_LIST_SUCCESS = "EXERCISE_LIST_SUCCESS";
export const EXERCISE_LIST_FAIL = "EXERCISE_LIST_FAIL";

export const EXERCISE_DELETE_REQUEST = "EXERCISE_DELETE_REQUEST";
export const EXERCISE_DELETE_SUCCESS = "EXERCISE_DELETE_SUCCESS";
export const EXERCISE_DELETE_FAIL = "EXERCISE_DELETE_FAIL";
